### ISSUE TITLE
>v1.0.0 versions not pushed to Plugin and Content Manager

### ISSUE THREAD

**Issue by globalcitizen** [bennymeg/JLC-Plugin-for-KiCad#10]
FYI the latest versions are not available in the Plugin and Content Manager. I guess you can somehow get this done by request.

<img width="923" alt="Screen Shot 2022-08-31 at 13 34 49" src="https://user-images.githubusercontent.com/505366/187600053-c6b797f2-4ebc-47ee-a07b-91b2e9beedc7.png">

**Comment by bennymeg** [comment]
Yes, I know, tnx.
The reason is that KiCad developers won't look at PR's if they do not pass the CI pipeline (even if you run the pipeline locally on your machine); And Gitlab requires a credit card to run pipelines. I am looking for someone with an verified Gitlab account to run the pipeline so the PR's would be accepted.

**Comment by bennymeg** [comment]
Thank you for asking.
I am happy to see that they are not requiring developers to run CI on Gitlab.
De facto, I think that is not the case. I am running their local package test they wrote on every release, and state in the PR I've done it. They do not address PR that are not flagged as passed the online CI pipeline unless you start a conversation on each PR. 
I will make a new PR for the latest release and see how it will go.

**Comment by bennymeg** [comment]
https://gitlab.com/kicad/addons/metadata/-/merge_requests/113

**Comment by bennymeg** [comment]
Well, it worked.
It got merged by the developer your talked to.
